version: '3.8'

services:
  msr-lean:
    image: ${TEST_CONTAINER_IMAGE}
    ports:
      - ${HOST_PORT_PREFIX}55:5555
    volumes:
      - ${MY_MSR_LICENSE_FILE}:/tmp/license.xml
      - /application.properties:/tmp/application.properties
      - ../../:/mnt/project-home/
      - ./local/:/mnt/local/
    #  - ./scripts/:/mnt/scripts/
    # Our packages
      - ../../code/is-packages/MyNewsService/:${GUEST_IS_HOME}/packages/MyNewsService/
      - ../../code/is-packages/MyMailService/:${GUEST_IS_HOME}/packages/MyMailService/
    environment:
      - SAG_IS_LICENSE_FILE=/tmp/license.xml
      - SAG_IS_CONFIG_PROPERTIES=/tmp/application.properties
      - SMTP_HOST_NAME
      - SMTP_HOST_PORT
      - SMTP_USER_EMAIL
      - SMTP_USER_PASS
      # NewsAPI service
      - NEWSAPI_BASE_URL
      - NEWSAPI_API_KEY
      - PUSH_TO_EMAIL
    #entrypoint: /mnt/scripts/entrypoint.sh